### ISSUE TITLE
report itsnebulalol

### ISSUE THREAD

**Issue by yairarad10** [ClientPlayground/Lightning-Client#1]
Hi there! so im a developer called s3dk and i made a minecraft client with my friend,so i saw someone posting my client on github with no credits and nothing like they stalled my client!,so i saw that they did it to a lot of clients like badlion laby mod and more! but the problem with this is they putting viruses on it! so i saw the name and he was on my discord server sending the link and his github name is itsnebulalol and i saw that his working for clientplayground 
![image](https://user-images.githubusercontent.com/49103194/115223172-2e1cf680-a114-11eb-9b72-6db5cae3b765.png) so if you could pls remove my client(lightning client) or maybe stop them for doing it!

**Comment by itsnebulalol** [comment]
There are no viruses in this leak, stop being a skid and code your own client. Or get a better obfuscator next time.

Thanks,
Dominic

**Comment by yairarad10** [comment]
its not ur clients why ur so gay just make ur own

**Comment by yairarad10** [comment]
and ik u made this client playground and like i said but u blocked me cuz ur a fucking pussy we have a new code coming and its not a skid and u telling me that badlion is skid? or lunar or laby mod?

**Comment by HyptexPvP** [comment]
> and ik u made this client playground and like i said but u blocked me cuz ur a fucking pussy we have a new code coming and its not a skid and u telling me that badlion is skid? or lunar or laby mod?

then stop worrying about your "code" being leaked then? you have new code coming out either way, also litreally 80% of your code is erics, stop saying it isnt

**Comment by itsnebulalol** [comment]
Stop, you are just some random fucking skid. You don't matter

**Comment by itsnebulalol** [comment]
Also, Badlion is here because they were pedophiles. And laby was exposed to be a skid. Lunar is a CB paste
